apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workloads
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app: product-catalog-svc
  backstage.io/kubernetes-id: product-catalog-svc
images:
  - name: to-be-replaced
    newName: ghcr.io/nicpym/product-catalog-svc
    newTag: v0.0.13
